# Trondheim weather data, 2014â€“present (including forecast)

## Download and preparation

In [2]:
import os
import met_forecast_data as forecast
import frost_historical_data


pwd = os.getcwd()

## Forecast for next nine days
The forecast is fetched through the product "Locationforecast" v1.9 of the MET Norway Weather API.

The data fetch and export script is self contained and can be run directly, but we will also load the data here to inspect it.

In [3]:
%run "./met_forecast_data.py"

In [4]:
forecast_df, forecast_created = forecast.create_forecast_dataframe()
print(forecast_created) # This is when the forecast was generated by MET
forecast_df.head()

2019-03-03T07:06:20Z

,humidity,pressure,rain,temperature,wind_from_direction,wind_speed
timestamp,,,,,,
2019-03-03 08:00:00,76.2,986.8,0.0,-0.1,3,2.2
2019-03-03 09:00:00,70.0,986.7,0.0,1.6,3,3.1
2019-03-03 10:00:00,67.6,986.3,0.0,2.8,3,5.1
2019-03-03 11:00:00,68.8,986.3,0.0,2.6,3,5.2
2019-03-03 12:00:00,69.6,986.6,0.0,2.4,3,4.2

In [5]:
forecast_df.tail()

,humidity,pressure,rain,temperature,wind_from_direction,wind_speed
timestamp,,,,,,
2019-03-11 06:00:00,81.7,996.3,0.0,-3.6,3,3.2
2019-03-11 12:00:00,60.2,994.7,0.0,1.0,6,4.5
2019-03-11 18:00:00,70.9,995.9,0.0,0.1,3,4.3
2019-03-12 00:00:00,76.8,996.3,0.0,-1.8,3,4.0
2019-03-12 06:00:00,80.7,994.1,0.0,-1.9,2,3.6

## Historical data from 2014 to present
The historical weather measurement data are fetched via the Frost API of Meteorologisk Institutt. 

Again, the data fetch and export script is self contained and can be run directly, but we will also load the data here to inspect it.

**Unfortunately, for some reason frost.met.no seems to be unstable today, so data fetch might not work live.**

In [ ]:
%run "./frost_historical_data.py"

In [6]:
measurements_df = frost_historical_data.measurements_to_df()
measurements_df.head()

Fetching from source: https://frost.met.no/observations/v0.jsonld?sources=SN68860&referencetime=2014-01-01/2015-01-01&elements=relative_humidity, surface_air_pressure, precipitation_amount, air_temperature, wind_from_direction, wind_speed, dew_point_temperature, cloud_area_fraction
Fetching from source: https://frost.met.no/observations/v0.jsonld?sources=SN68860&referencetime=2015-01-01/2016-01-01&elements=relative_humidity, surface_air_pressure, precipitation_amount, air_temperature, wind_from_direction, wind_speed, dew_point_temperature, cloud_area_fraction
Fetching from source: https://frost.met.no/observations/v0.jsonld?sources=SN68860&referencetime=2016-01-01/2017-01-01&elements=relative_humidity, surface_air_pressure, precipitation_amount, air_temperature, wind_from_direction, wind_speed, dew_point_temperature, cloud_area_fraction
Fetching from source: https://frost.met.no/observations/v0.jsonld?sources=SN68860&referencetime=2017-01-01/2018-01-01&elements=relative_humidity, surface_air_pressure, precipitation_amount, air_temperature, wind_from_direction, wind_speed, dew_point_temperature, cloud_area_fraction
Fetching from source: https://frost.met.no/observations/v0.jsonld?sources=SN68860&referencetime=2018-01-01/2019-01-01&elements=relative_humidity, surface_air_pressure, precipitation_amount, air_temperature, wind_from_direction, wind_speed, dew_point_temperature, cloud_area_fraction
Fetching from source: https://frost.met.no/observations/v0.jsonld?sources=SN68860&referencetime=2019-01-01/2019-03-03&elements=relative_humidity, surface_air_pressure, precipitation_amount, air_temperature, wind_from_direction, wind_speed, dew_point_temperature, cloud_area_fraction

,air_temperature,cloud_area_fraction,dew_point_temperature,relative_humidity,surface_air_pressure,wind_from_direction,wind_speed
timestamp,,,,,,,
2014-01-01 00:00:00,1.3,0.0,-0.7,86,988.9,5,1.1
2014-01-01 01:00:00,1.7,NaN,-2.2,75,988.9,4,1.2
2014-01-01 02:00:00,0.4,NaN,-2.2,83,988.8,5,0.8
2014-01-01 03:00:00,1.8,0.0,-3.6,67,988.1,5,2.2
2014-01-01 04:00:00,1.2,NaN,-3.8,69,987.2,2,1.4

In [8]:
measurements_df.tail()

,air_temperature,cloud_area_fraction,dew_point_temperature,relative_humidity,surface_air_pressure,wind_from_direction,wind_speed
timestamp,,,,,,,
2019-03-02 19:00:00,-1.1,NaN,-2.2,93,981.5,1,1.5
2019-03-02 20:00:00,-1.1,NaN,-1.9,94,980.9,1,2.2
2019-03-02 21:00:00,-1.1,NaN,-2.2,93,980.0,1,1.4
2019-03-02 22:00:00,-1.1,NaN,-2.2,92,979.2,1,2.9
2019-03-02 23:00:00,-1.2,NaN,-1.9,94,978.3,1,2.7

In [9]:
#Backup:
#measurements_df = pd.read_csv("./data/data_archive/frost_measurement_data_2014-2019.csv", header=0, index_col=0)
#measurements_df.head()

The wind direction data is simplified from continuous to discrete directions ("N", "SE" etc.), and then encoded from 0 through 7, starting at "N".

# Other data sources
Given more time, we would have fetched traffic data from "Nasjonal vegdatabank", and better measurement and forecast data for cloud coverage.